name: imitatio
description: Generate different types of fake data in multiple languages.
version: 1.2.0
homepage: https://github.com/SkinnyMind/imitatio

environment:
  sdk: ^3.10.0

dependencies:
  crypto: ^3.0.3
  os_detect: ^2.0.3

dev_dependencies:
  custom_lints:
    git: https://github.com/SkinnyMind/custom_lints
  test: ^1.25.1
